### PR TITLE
All 0.2 features

### PR DESCRIPTION
**Pull request by Portponky**
Merging the following features back to main:

* Decorations
* Terrain icons
* Randomization updates

This will cause an update from 0.1 version to 0.2 version for terrain metadata. This is ready to go on main. I'll leave this up for a short while in case anyone wants to test it, and whilst I do some testing of my own. I'll be merging this very soon, though.

### CODE REVIEW

**Comment by Portponky** [comment]
Should I move the grid button down here?

image

Saves a bunch of space, nice on smaller screens.

**Comment by torcado194** [comment]
oh yes, definitely agree that button should be there! maybe with a vertical bar (the blank space suffices but might be clearer when width is minimized)

**Comment by Portponky** [comment]
I think I need to adjust how icons behave, as there is no distinction between "not changing an icon" and "setting an icon to nothing" in `set_terrain`, which causes issues in certain cases e.g. when you undo deleting a category that's in use.

**Comment by torcado194** [comment]
I've been testing the latest version (adding/removing terrains, testing icons, undo/redo, etc.) and I haven't found any issues yet. looks good to me!

**Comment by Portponky** [comment]
Confirmed, seems good. Merging.

**Pull request merged**
