### PR TITLE
Icons and decoration

### PR DESCRIPTION
**Pull request by torcado194**
Merges #21 and #22 and fixes conflicts.

I bumped the terrain version to 0.3 in order to handle converting the terrains I opened while testing both features, I hope that's fine.

### CODE REVIEW

**Comment by univeous** [comment]
Looks great!
I tested your PR, and it works but gives me a lot `res://addons/better-terrain/BetterTerrain.gd:274 - Invalid get index '4' (on base: 'Array').` errors when no decoration is set.

For the limited text length, maybe we can do something like this? I'm not sure if it's too fancy though.

Reference: [this](https://github.com/Ark2000/PankuConsole/blob/master/addons/panku_console/modules/data_controller/exporter/row_comment.tscn) and [this](https://github.com/Ark2000/PankuConsole/blob/master/addons/panku_console/modules/data_controller/exporter/row_ui_comment.gd)

https://github.com/Portponky/better-terrain/assets/40604180/b5059174-7e24-4bab-a143-e6bc832e24de

**Comment by torcado194** [comment]
Thanks for testing!

Hm, the modified `_update_terrain_data` should handle those conversion issues. Did you test either of the other PRs (#21 or #22) prior to this one for that project, or was that project running the stable version of the plugin before those changes?

Yeah, that's a nice solution but I think it's overkill for this case. If anything, it could have a hover-over tooltip that displays the full name (assuming Godot has a nice builtin for something like that).

**Comment by univeous** [comment]
I'm running the stable version before. Also I updated the previous comment in case you miss it :)
I think the grid size slider option can handle the text length too.

**Comment by torcado194** [comment]
I think the main benefit of grid mode is for compactness, like you said for cases where you have a ton of terrains to comb through, so adding features to make them bigger seems counter-productive to me. I think the name cutoff isn't that big of a deal after all (It could maybe even be removed entirely, since there's already several identifiers for the terrain)

**Comment by univeous** [comment]
The problem is the grid item may look too small on some hi-res monitors. Maybe not a slider, but an option to modify the grid item size instead of hardcode it.

Yeah I agree the text does not really matter, and I see you using `ellipsis` text overrun behavior, but it seems not working properly, which may cause some confusion. Maybe just hide it and use the tooltip which is pretty easy to add, just add `tooltip_text = terrain.name` in `update()` function in TerrainEntry and it works fine.

**Comment by torcado194** [comment]
I can't seem to reproduce the `Invalid get index '4'` issue you were having.
I started a new project, added the current stable version of better-terrain (a0ecd99), added terrains of each type, replaced the plugin with the version for this PR, and added/removed/painted with those terrains, and I never encountered that error. It's possible there was some conflict with one version or another, but I have no idea 🤷 

Yeah, not sure why ellipsis isn't working properly. it seems to break with short text.
I think that's a fine idea, and it distinguishes grid view even more from the list display. I'll look into making that change :)

**Comment by univeous** [comment]
I believe the problem is I have a tilemap1 using tileset1, and tilemap2 using tileset2, when I click tilemap1, somehow the plugin accessed the tileset2 whose metadata is not being updated yet. After I messed around the tileset2 is updated and the errors are gone. I can't find a stable way to reproduce this though.

**Comment by univeous** [comment]
when creating terrain in grid mode, a list item will be added.
I would say it's pretty cool though 🤣

image

**Comment by torcado194** [comment]
nice catch, fixed :)

**Comment by Portponky** [comment]
Closing, as it is rolled into https://github.com/Portponky/better-terrain/pull/26 which will be merged to main soon.

Note that any tileset terrains created using this branch will probably be in a invalid state with main/future versions.

**Pull request closed without merging**
